var fs   = require('fs');
var path = require('path');

module.exports = {
	
	// These are the starting point for arrays AkashaCMS uses to look for stuff
	
    root_assets: [ 'assets' ],
    root_layouts: [ 'layouts' ],
    root_partials: [ ],
    root_out: 'out',
    root_docs: [ 'documents'],
    
	root_url: "http://skeleton.akashacms.com",
	
	// AkashaCMS configuration data
    akashacmsEPUB: {
        
		// List of files which will be autogenerated ...
		
        files: {
            opf: "skeleton.opf",	// The OPF file contains metadata and navigation stuff
            // ncx: "toc.ncx",			// Auto-generated out of the manifest, navigation info comes from toc data
            // toc: "toc",				// Auto-generated out of the manifest, using toc data
			//						// The file name written to is in the manifest entry identified by this id=
            epub: "skeleton.epub"	// Autogenerated and containing the files listed in the manifest
        },
        
		// Fills in the metadata element in the OPF file
		
        metadata: {
            title: "Skeletal AkashaEPUB book",
            languages: [ "en" ],
            identifiers: [
                {
                    // Rather than pay for an ISBN we'll use this
                    unique: true,
                    idstring: "urn:uuid:b624d2ee-e88a-11e4-b0db-376a7655914b",
                    // Keep for testing ... ncxidentifier: "urn:uuid:d475c10e-e88a-11e4-bb13-5bd68dc03c1f"
                },
                /* { // Keep this one for testing
                    idstring: "urn:uuid:e343c316-e88a-11e4-8c3f-977288b3fef7"
                } */
            ],
            creators: [
                {  id: "author", name: "John Smith", nameReversed: "Smith, John" },
            ],
            publisher: "AkashaCMS.COM",
            subjects: [ "Reference" ],
            cover: "ebook-cover-image",
            rights: "Public DOmain"
        },
		
        cover: {
            id: "cover",
            idImage: "cover-image",
            // src:  "images/epub-guide-cover.png",
            src:  "images/Human-Skeleton.jpg",
            alt:  "AkashaEPUB Skeleton Book",
            type: "image/jpeg"
        },
        
        contents: {
            id: "toc",
            title: "Table of Contents",
            subtitle: undefined,
            href: "toc.html",
            path: "toc.html.ejs",
            type: "application/xhtml+xml",
            toclayout: "epub_page.html.ejs",
            
            ncx: {
                id: "ncx",
                href: "toc.ncx"
            }
        },
        
        chapters: [
            {
                id: "chapter1",
                title: "Introduction to AkashaEPUB",
                href: "chap1.html",
                type: "application/xhtml+xml",
                navclass: "book",
                
                subchapters: [
                    {
                        id: "chapter1a",
                        title: "Installing Node.js, AkashaCMS and AkashaEPUB",
                        href: "chap1a.html",
                        type: "application/xhtml+xml",
                        navclass: "book"
                    }
                ]
            },
            {
                id: "chapter2",
                title: "Creating content for an AkashaEPUB",
                href: "chap2.html",
                type: "application/xhtml+xml",
                navclass: "book"
            },
            {
                id: "chapter3",
                title: "Configuration",
                href: "chap3.html",
                type: "application/xhtml+xml",
                navclass: "book",
                
                subchapters: [
                    {
                        id: "chapter3a",
                        title: "Configuration",
                        href: "chap3a.html",
                        type: "application/xhtml+xml",
                        navclass: "book"
                    },
                    {
                        id: "chapter3b",
                        title: "Configuration",
                        href: "chap3b.html",
                        type: "application/xhtml+xml",
                        navclass: "book"
                    }
                ]
            },
            {
                id: "chapter4",
                title: "Configuration",
                href: "chap4.html",
                type: "application/xhtml+xml",
                navclass: "book"
            }
        ],
        
        stylesheets: [
            { id: "stylesheet", href: "css/style.css", type: "text/css" }
        ],
        
        assets: [
        ]
    },
    
    data: {
    },
    
	google: {
	},
    
    headerScripts: {
        stylesheets: [ ],
        javaScriptTop: [ ],
        javaScriptBottom: [ ]
    },
	
    funcs: {
    },

    cheerio: {
        recognizeSelfClosing: true,
        recognizeCDATA: true,
        xmlMode: true
    },
    
	// For EPUB's we need to suppress a lot of standard AkashaCMS behavior
    builtin: {
        suppress: {
            layouts: true,
            // partials: true,
            assets: true,
            sitemap: true,
            extlink: true
        }
    },
	
    config: function(akasha) {
		akasha.registerPlugins(module.exports, [
            { name: 'akashacms-epub', plugin: require('akashacms-epub') }
		]);
    }
};
