var fs   = require('fs');
var path = require('path');

module.exports = {
	
	// These are the starting point for arrays AkashaCMS uses to look for stuff
	
    root_assets: [ 'assets' ],
    root_layouts: [ 'layouts' ],
    root_partials: [ ],
    root_out: 'out',
    root_docs: [ 'documents'],
    
	root_url: "http://skeleton.akashacms.com",
	
	// AkashaCMS configuration data
    akashacmsEPUB: {
        
		// List of files which will be autogenerated ...
		
        files2generate: {
            opf: "skeleton.opf",	// The OPF file contains metadata and navigation stuff
            ncx: "toc.ncx",			// Auto-generated out of the manifest, navigation info comes from toc data
            toc: "toc",				// Auto-generated out of the manifest, using toc data
									// The file name written to is in the manifest entry identified by this id=
            epub: "skeleton.epub"	// Autogenerated and containing the files listed in the manifest
        },
        
		// Fills in the metadata element in the OPF file
		
        metadata: {
            title: "Skeletal AkashaEPUB book",
            languages: [ "en" ],
            ISBN: "urn:isbn:123456789X",
            identifier: "urn:isbn:123456789X",
            creators: [
                { name: "John Smith", nameReversed: "Smith, John" },
            ],
            publisher: "Amazon.com",
            subjects: [ "Reference" ],
            date: "2015-02-21",
            modified: "2015-02-26T00:00:00Z",
            cover: "ebook-cover-image",
            rights: "None"
        },
		
		// Fills in the manifest element in the OPF file
		//
		// The spineorder entries control the order these appear in the spine element
        
        manifest: [
            {
                id: "cover",
                title: "Cover",
                href: "cover.html",
                type: "application/xhtml+xml",
                spineorder: 1
            },
            {
				// The id= must match the string in files2generate.toc above
				// There is no toc.html.ejs in the files, instead that file is autogenerated
				// and is written out as toc.html
				// The toclayout entry controls the page layout for the Table of Contents page
				
                id: "toc",
                title: "Table of Contents",
                href: "toc.html",
                path: "toc.html.ejs",
                type: "application/xhtml+xml",
                spineorder: 2,
                navclass: "toc",
                toclayout: "page.html.ejs",
                properties: "nav"
            },
            {
                id: "ncx",
                href: "toc.ncx",
                type: "application/x-dtbncx+xml",
                spinetoc: true,
                navclass: "toc"
            },
            {
                id: "chapter1",
                title: "Introduction to AkashaEPUB",
                href: "chap1.html",
                type: "application/xhtml+xml",
                spineorder: 3,
                navclass: "book"
            },
            {
                id: "chapter1a",
                title: "Installing Node.js, AkashaCMS and AkashaEPUB",
                href: "chap1a.html",
                type: "application/xhtml+xml",
                spineorder: 4,
                navclass: "book"
            },
            {
                id: "chapter2",
                title: "Creating content for an AkashaEPUB",
                href: "chap2.html",
                type: "application/xhtml+xml",
                spineorder: 5,
                navclass: "book"
            },
            {
                id: "chapter3",
                title: "Configuration",
                href: "chap3.html",
                type: "application/xhtml+xml",
                spineorder: 6,
                navclass: "book"
            },
            {
                id: "chapter3a",
                title: "Configuration",
                href: "chap3a.html",
                type: "application/xhtml+xml",
                spineorder: 7,
                navclass: "book"
            },
            {
                id: "chapter3b",
                title: "Configuration",
                href: "chap3b.html",
                type: "application/xhtml+xml",
                spineorder: 8,
                navclass: "book"
            },
            {
                id: "chapter4",
                title: "Configuration",
                href: "chap4.html",
                type: "application/xhtml+xml",
                spineorder: 9,
                navclass: "book"
            },
            { id: "stylesheet", href: "css/style.css", type: "text/css" },
            {
                id: "ebook-cover-image",
                properties: "cover-image",
                href: "images/Human-Skeleton.jpg",
                type: "image/jpeg"
            }
        ],
        
		// This controls the hierarchy of items in the table of contents,
		// both in the toc.html and toc.ncx files
		//
		// The id: strings here have to match id: values in the manifest, and the information
		// in the matching manifest entry is used in creating the correct table of contents entries.
		
        toc: [
            { id: "cover" },
            { id: "toc" },
            {
                id: "chapter1",
                subtoc: [
                    { id: "chapter1a" }
                ]
            },
            {
                id: "chapter2"
            },
            {
                id: "chapter3",
                subtoc: [
                    { id: "chapter3a" },
                    { id: "chapter3b" }
				]
            },
            {
                id: "chapter4"
            }
        ],
        
        stylesheets: [
            { href: "css/style.css" }
        ]
    },
    
    data: {
    },
    
	google: {
	},
    
    headerScripts: {
        stylesheets: [ ],
        javaScriptTop: [ ],
        javaScriptBottom: [ ]
    },
	
    funcs: {
    },

    cheerio: {
        recognizeSelfClosing: true,
        recognizeCDATA: true,
        xmlMode: true
    },
    
	// For EPUB's we need to suppress a lot of standard AkashaCMS behavior
    builtin: {
        suppress: {
            layouts: true,
            // partials: true,
            assets: true,
            sitemap: true,
            extlink: true
        }
    },
	
    config: function(akasha) {
		akasha.registerPlugins(module.exports, [
            { name: 'akashacms-epub', plugin: require('akashacms-epub') }
		]);
    }
};
